"""Extract only a specifically requested user message's assets, without recompression.

Run explicitly against the current conversation file; never export whole chat history.
"""
import argparse
import base64
import hashlib
import json
from pathlib import Path

parser=argparse.ArgumentParser()
parser.add_argument('--session-file',type=Path,required=True)
parser.add_argument('--output',type=Path,required=True)
args=parser.parse_args()
match=None
with args.session_file.open(encoding='utf-8') as stream:
    for line in stream:
        if '你现在无需生成图片' not in line: continue
        record=json.loads(line);p=record.get('payload',{})
        if record.get('type')!='response_item' or p.get('role')!='user':continue
        text='\n'.join(c['text'] for c in p.get('content',[]) if c.get('type')=='input_text')
        images=[c['image_url'] for c in p.get('content',[]) if c.get('type')=='input_image']
        if 'M98 Android Smart TV Stick' in text and len(images)==16:match=(text,images)
if match is None:raise SystemExit('Requested 16-image user message not found; no files written.')
args.output.mkdir(parents=True,exist_ok=True)
text,images=match
def save(name,content):
    target=args.output/name
    if target.exists():
        if target.read_bytes()!=content:raise SystemExit('Existing artifact differs: '+name)
    else:
        with target.open('xb') as stream:stream.write(content)
    return {'name':name,'sha256':hashlib.sha256(content).hexdigest(),'bytes':len(content)}
manifest=[]
manifest.append(save('user-copy-original.txt',text.encode('utf-8')))
title=text.split('标题：',1)[1].split('主图：',1)[0].strip()
description=text.split('详情介绍：',1)[1].split('详情图：',1)[0].strip()
manifest.append(save('title.txt',title.encode('utf-8')))
manifest.append(save('description.md',description.encode('utf-8')))
for i,image in enumerate(images,1):
    prefix,encoded=image.split(',',1)
    if prefix!='data:image/png;base64':raise SystemExit('Unexpected attachment format; refusing conversion.')
    manifest.append(save(f'{i:02}.png',base64.b64decode(encoded,validate=True)))
save('manifest.json',json.dumps({'source':'user-provided finished example; not generated by workbench',
    'order':'01 main; 02-09 secondary; 10-16 detail','files':manifest},ensure_ascii=False,indent=2).encode('utf-8'))
print(json.dumps({'folder':str(args.output),'images':16,'title_characters':len(title),'copied_without_reencoding':True},ensure_ascii=False))
